### ISSUE TITLE
Support `onResolve` pipe

### ISSUE THREAD

**Issue by He110te4m** [sxzz/esbuild-plugin-transform#28]
### Clear and concise description of the problem

When I used `esbuild-vue` + `unplugin-auto-import` to build the project, the build didn't work.
Because `onResolve` is used in `esbuild-vue`, it won't work properly when placed in the transform plugin.

### Suggested solution

Add onResolve support in `esbuild-plugin-transform`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Comment by He110te4m** [comment]
I found the problem.

Because I am using a multi-entry build, the transformed files are not differentiated by entry.

What causes Vue to receive is not the SFC, but the processed source file.

So the later entry builds are all exceptions.

My entryPoint configuration is as follows:

```
[
  './src/routes.ts',
  './src/views/Home.vue',
]
```

I tried to build the dynamically imported `home.vue` in the router separately.

Because I need to reuse this component (in the form of a module federation) .

**Comment by He110te4m** [comment]
I found the problem. Because I used multi-entry + dynamic import.

Dynamic import is treated as an entry.

This entry is duplicated with multiple entries configured separately, so that a file is processed multiple times.

My scenario uses module federation, which is configured as follows:

Since Home needs to be imported dynamically in routes and exposed as a separate component, it also needs to be configured as entryPoint.

At this point, esbuild builds Home twice, and the output from both builds is cached by transform, causing the plug-in to duplicate the file.

So the source file esbuild-vue receives the second time is the processed JS code, not the SFC.

As a result, the resulting Home is an empty file.

**Comment by He110te4m** [comment]
I modify the code locally.

I use the pluginName and entryPoints as the unique ids.

When the ID exists, [the plugin's onLoad method is not added](https://github.com/sxzz/esbuild-plugin-transform/blob/main/src/index.ts#L26).

It will solve the problem.

**Comment by He110te4m** [comment]
The reason for the problem is [this line](https://github.com/sxzz/esbuild-plugin-transform/blob/main/src/index.ts#L16).

Because onLoads is not cleared, the plugin onLoad is registered repeatedly on multiple calls to setup (multiple entries) .

Just move this line of code into setup to resolve it.

**Comment by sxzz** [comment]
Thanks for your feedback. Fixed and release in esbuild-plugin-transform@0.5.0
